service: docuverify-backend
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.11
  stage: dev
  region: us-east-1
  memorySize: 128

functions:
  app:
    handler: handler.upload
    events:
      - http: ANY /
      - http: "ANY {proxy+}"

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
